// This file is generated by scripts/generate-authors-from-community-contributors.mjs.
// Do not edit manually.

export const authorEntries = [
  {
    key: "abhayprince",
    displayName: "Abhay Prince",
  },
  {
    key: "adospace",
    displayName: "Adolfo Marinucci",
  },
  {
    key: "AgustinBonilla",
    displayName: "Agustin Bonilla",
  },
  {
    key: "albyrock87",
    displayName: "Alberto Aldegheri",
  },
  {
    key: "Alexgoon",
    displayName: "Alexander Russkov",
  },
  {
    key: "almirvuk",
    displayName: "Almir Vuk",
  },
  {
    key: "alyssamichelle",
    displayName: "Alyssa Nicoll",
  },
  {
    key: "andreas-nesheim",
    displayName: "Andreas Nesheim",
  },
  {
    key: "AntPolkanov",
    displayName: "Anton Polkanov",
  },
  {
    key: "aritchie",
    displayName: "Allan Ritchie",
  },
  {
    key: "bijington",
    displayName: "Shaun Lawrence",
  },
  {
    key: "bradystroud",
    displayName: "Brady Stroud",
  },
  {
    key: "Calinciurariu",
    displayName: "Calin Ciurariu",
  },
  {
    key: "Char0394",
    displayName: "Charlin Agramonte",
  },
  {
    key: "CliffAgius",
    displayName: "Clifford Agius",
  },
  {
    key: "codemillmatt",
    displayName: "Matt Soucoup",
  },
  {
    key: "codrinamerigo",
    displayName: "Codrina Merigo",
  },
  {
    key: "csaba8472",
    displayName: "Csaba Huszár",
  },
  {
    key: "damianantonowicz",
    displayName: "Damian Antonowicz",
  },
  {
    key: "damiendoumer",
    displayName: "Damien Doumer",
  },
  {
    key: "danielmonettelli",
    displayName: "Daniel Monettelli",
  },
  {
    key: "dansiegel",
    displayName: "Dan Siegel",
  },
  {
    key: "davidnsai",
    displayName: "David Nsai",
  },
  {
    key: "davidortinau",
    displayName: "David Ortinau",
  },
  {
    key: "dellis1972",
    displayName: "Dean Ellis",
  },
  {
    key: "dhindrik",
    displayName: "Daniel Hindrikes",
  },
  {
    key: "dirivero",
    displayName: "Diego Rivero",
  },
  {
    key: "dotnet",
    displayName: ".NET",
  },
  {
    key: "dotnet-foundation",
    displayName: ".NET Foundation",
  },
  {
    key: "dotnetMAUIPodcast",
    displayName: "The .NET MAUI Podcast",
    imagePath: "/img/contributors/dotnetMAUIPodcast.jpg",
    disableGitHubProfileLink: true,
  },
  {
    key: "drasticactions",
    displayName: "Tim Miller",
  },
  {
    key: "eschimmel",
    displayName: "Ed Schimmel",
  },
  {
    key: "EstebanP-dev",
    displayName: "Juan Esteban Navia",
  },
  {
    key: "ewerspej",
    displayName: "Julian Ewers-Peters",
  },
  {
    key: "fdmomtaz",
    displayName: "Farshad Momtaz",
  },
  {
    key: "flaviogoncalves",
    displayName: "Flavio Gonclaves",
  },
  {
    key: "framinosona",
    displayName: "François Raminosona",
  },
  {
    key: "freakyali",
    displayName: "Gulam Ali H.",
  },
  {
    key: "HorusSoftwareUY",
    displayName: "Horus Software",
  },
  {
    key: "hot33331",
    displayName: "Tobias Hoppenthaler",
  },
  {
    key: "hprez21",
    displayName: "Héctor Pérez ",
  },
  {
    key: "icebeam7",
    displayName: "Luis Antonio Beltran Prieto",
  },
  {
    key: "ihassantariq",
    displayName: "Hafiz Muhammad Hassan",
  },
  {
    key: "ilija2407",
    displayName: "Ilija Rushkovski",
  },
  {
    key: "its-AliRaza",
    displayName: "Ali Raza",
  },
  {
    key: "jamesmontemagno",
    displayName: "James Montemagno",
  },
  {
    key: "JaneySprings",
    displayName: "Nikita Romanov",
  },
  {
    key: "jasho",
    displayName: "Roman Jasek",
  },
  {
    key: "jBijsterboschNL",
    displayName: "John Bijsterbosch",
  },
  {
    key: "jfversluis",
    displayName: "Gerald Versluis",
  },
  {
    key: "JohanSmarius",
    displayName: "Johan Smarius",
  },
  {
    key: "jonathanpeppers",
    displayName: "Jonathan Peppers",
  },
  {
    key: "jsuarezruiz",
    displayName: "Javier Suárez",
  },
  {
    key: "Kapusch",
    displayName: "Jean-Emmanuel BAILLAT",
  },
  {
    key: "Kode4Hue",
    displayName: "Hubert Graham",
  },
  {
    key: "kubaflo",
    displayName: "Jakub Florkowski",
  },
  {
    key: "LeomarisReyes",
    displayName: "Leomaris Reyes",
  },
  {
    key: "liamelliott",
    displayName: "Liam Elliott",
  },
  {
    key: "lothrop",
    displayName: "Kerry W. Lothrop",
  },
  {
    key: "luismts",
    displayName: "Luis Matos",
  },
  {
    key: "maddymontaquila",
    displayName: "Maddy Montaquila",
  },
  {
    key: "mallibone",
    displayName: "Mark Allibone",
  },
  {
    key: "matt-goldman",
    displayName: "Matt Goldman",
  },
  {
    key: "matthewrdev",
    displayName: "Matthew Robbins",
  },
  {
    key: "mattjohnsonpint",
    displayName: "Matt Johnson-Pint",
  },
  {
    key: "mattleibow",
    displayName: "Matthew Leibowitz",
  },
  {
    key: "MaxMa04",
    displayName: "Max Mannstein",
  },
  {
    key: "melissahoughton",
    displayName: "Melissa Houghton",
  },
  {
    key: "michaelstonis",
    displayName: "Michael Stonis",
  },
  {
    key: "morning4coffe-dev",
    displayName: "Dominik Titl",
  },
  {
    key: "mrlacey",
    displayName: "Matt Lacey",
  },
  {
    key: "naweed",
    displayName: "Naweed Akram",
  },
  {
    key: "ne0rrmatrix",
    displayName: "James Crutchley",
  },
  {
    key: "NickA55",
    displayName: "Nick Alonge",
  },
  {
    key: "PaulAndersonS",
    displayName: "Paul Anderson",
  },
  {
    key: "pictos",
    displayName: "Pedro Jesus",
  },
  {
    key: "plattski",
    displayName: "David Platt",
  },
  {
    key: "praeclarum",
    displayName: "Frank A. Krueger ",
  },
  {
    key: "PureWeen",
    displayName: "Shane Neuville",
  },
  {
    key: "rachelkang",
    displayName: "Rachel Kang",
  },
  {
    key: "Redth",
    displayName: "Jonathan Dick",
  },
  {
    key: "roubachof",
    displayName: "Jean-Marie Alfonsi",
  },
  {
    key: "saamerm",
    displayName: "Saamer Mansoor",
  },
  {
    key: "samidip",
    displayName: "Sam Basu",
  },
  {
    key: "SirJohnK",
    displayName: "Johan Svensson",
  },
  {
    key: "SkJonko",
    displayName: "Antonis Kotis ",
  },
  {
    key: "StephaneDelcroix",
    displayName: "Stéphane Delcroix",
  },
  {
    key: "sthewissen",
    displayName: "Steven Thewissen",
  },
  {
    key: "Sweekriti91",
    displayName: "Sweeky Satpathy",
  },
  {
    key: "syncfusion",
    displayName: "Syncfusion",
  },
  {
    key: "taublast",
    displayName: "Nick Kovalsky",
  },
  {
    key: "TheCodeTraveler",
    displayName: "Brandon Minnick",
  },
  {
    key: "tije709",
    displayName: "TJ Lambert",
  },
  {
    key: "tkapa",
    displayName: "Tylah Kapa",
  },
  {
    key: "Toine-db",
    displayName: "Toine de Boer",
  },
  {
    key: "tonyedwardspz",
    displayName: "Tony Edwards",
  },
  {
    key: "tsjdev-apps",
    displayName: "Sebastian Jensen",
  },
  {
    key: "unoplatform",
    displayName: "Uno Platform",
  },
  {
    key: "vhugogarcia",
    displayName: "Victor Hugo Garcia",
  },
  {
    key: "VladislavAntonyuk",
    displayName: "Vladislav Antonyuk",
  },
  {
    key: "zleao",
    displayName: "José Pereira",
  }
] as const;
