// This file is generated by scripts/fetch-mauiverse-website-contributors.mjs.
// Do not edit manually.

export const mauiverseWebsiteContributorSource = "https://api.github.com/repos/MAUIverse/mauiverse.net/contributors?per_page=100";
export const mauiverseWebsiteContributorFetchedAt = "2026-04-06T10:14:55.315Z";
export const mauiverseWebsiteContributorUsernames = [
  "jfversluis",
  "kubaflo",
  "seba47",
  "tonyedwardspz"
] as const;
