// This file is generated by scripts/fetch-mauiverse-website-contributors.mjs.
// Do not edit manually.

export const mauiverseWebsiteContributorSource = "https://api.github.com/repos/MAUIverse/mauiverse.net/contributors?per_page=100";
export const mauiverseWebsiteContributorFetchedAt = "2026-02-20T13:30:41.418Z";
export const mauiverseWebsiteContributorUsernames = [
  "jfversluis"
] as const;
