// This file is generated by scripts/fetch-nuget-authors.mjs.
// Do not edit manually.

export const nugetAuthorSource = "https://azuresearch-usnc.nuget.org/query?q=owner:<github-username>&prerelease=false&take=1";
export const nugetAuthorFetchedAt = "2026-02-19T14:32:47.897Z";
export const nugetAuthorUsernames = [
  "abhayprince",
  "adospace",
  "alexgoon",
  "aritchie",
  "bijington",
  "damianantonowicz",
  "damiendoumer",
  "dansiegel",
  "dhindrik",
  "ewerspej",
  "flaviogoncalves",
  "framinosona",
  "freakyali",
  "jamesmontemagno",
  "jfversluis",
  "jonathanpeppers",
  "jsuarezruiz",
  "luismts",
  "mallibone",
  "matt-goldman",
  "mrlacey",
  "naweed",
  "nicka55",
  "pureween",
  "redth",
  "roubachof",
  "sirjohnk",
  "sthewissen",
  "taublast",
  "toine-db",
  "tsjdev-apps",
  "unoplatform",
  "zleao"
] as const;
