// This file is generated by scripts/fetch-syncfusion-maui-toolkit-contributors.mjs.
// Do not edit manually.

export const syncfusionMauiToolkitContributorSource = "https://api.github.com/repos/syncfusion/maui-toolkit/contributors?per_page=100";
export const syncfusionMauiToolkitContributorFetchedAt = "2026-02-20T10:26:30.308Z";
export const syncfusionMauiToolkitContributorUsernames = [
  "anandh-sf4665",
  "aruljenithberkmans",
  "arunachalam406",
  "brundhasf3969",
  "chozarajan-p",
  "dhanarajrajendran",
  "edberg-vasan",
  "farjanaparveen",
  "felicity-r",
  "hadayarahman-sf4673",
  "harsha-sf4223",
  "jahnavi-sf4672",
  "jeyasri-murugan",
  "kamalesh-periyasamy",
  "karthikarsf4617",
  "karthikasf4617",
  "kishore4299",
  "leojharris",
  "mohamedhasan3644",
  "monika4841",
  "muniappansubramanian",
  "naveenkumar-sanjeevirayan",
  "paulandersons",
  "prithisiyyappan",
  "prithissf3973",
  "rasikapalanisamy",
  "saiganesh-sakthivel",
  "sanjaysf4372",
  "saravanan-madhesh",
  "sathish-087",
  "shalinisf79",
  "shyamsundar-sf4699",
  "simoncropp",
  "subash-sf",
  "surya3655"
] as const;
